#!/usr/bin/env bash
#
# share_to_browser.sh <url>
#
# Presents a zenity list of pre-configured browsers and launches the one
# the user picks with the given URL.
#
# Browsers are configured in:
#   $XDG_CONFIG_HOME/share-to-other-browser/browsers.conf   (default: ~/.config/...)
#
# Format: one browser per line, "Display Name|command %u"
#   %u is replaced with the URL (as a single argv token, not shell-interpolated).
# Lines starting with # and blank lines are ignored.
#
# If the config file doesn't exist yet, it is auto-generated by probing
# for common browsers on $PATH.

set -euo pipefail

URL="${1:-}"
if [[ -z "$URL" ]]; then
    zenity --error --text="No URL was provided." 2>/dev/null || true
    exit 1
fi

if ! command -v zenity >/dev/null 2>&1; then
    # Nothing we can show the user with; just fail quietly to the log.
    echo "zenity is not installed" >&2
    exit 1
fi

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/share-to-other-browser"
CONFIG_FILE="$CONFIG_DIR/browsers.conf"

mkdir -p "$CONFIG_DIR"

# --- First run: auto-detect installed browsers and write a default config ---
if [[ ! -f "$CONFIG_FILE" ]]; then
    {
        echo "# Share to Other Browser - configured targets"
        echo "# Format: Display Name|command %u"
        echo "# %u is replaced with the shared URL."
        echo "#"
        command -v firefox              >/dev/null 2>&1 && echo "Firefox (new window)|firefox --new-window %u"
        command -v google-chrome-stable >/dev/null 2>&1 && echo "Google Chrome|google-chrome-stable %u"
        command -v google-chrome        >/dev/null 2>&1 && echo "Google Chrome|google-chrome %u"
        command -v chromium             >/dev/null 2>&1 && echo "Chromium|chromium %u"
        command -v chromium-browser     >/dev/null 2>&1 && echo "Chromium|chromium-browser %u"
        command -v brave-browser        >/dev/null 2>&1 && echo "Brave|brave-browser %u"
        command -v vivaldi              >/dev/null 2>&1 && echo "Vivaldi|vivaldi %u"
        command -v opera                >/dev/null 2>&1 && echo "Opera|opera %u"
        command -v qutebrowser          >/dev/null 2>&1 && echo "qutebrowser|qutebrowser %u"
        command -v epiphany             >/dev/null 2>&1 && echo "GNOME Web|epiphany %u"
        command -v torbrowser-launcher  >/dev/null 2>&1 && echo "Tor Browser|torbrowser-launcher %u"
    } | awk '!/^#/ && seen[$0]++ { next } { print }' > "$CONFIG_FILE"

    if ! grep -qv '^\s*#\|^\s*$' "$CONFIG_FILE"; then
        zenity --error --width=400 \
            --text="No browsers were auto-detected.\n\nEdit:\n$CONFIG_FILE\n\nand add lines like:\nGoogle Chrome|google-chrome-stable %u" \
            2>/dev/null || true
        exit 1
    fi
fi

# --- Parse config into parallel arrays ---
NAMES=()
COMMANDS=()
while IFS='|' read -r name cmd; do
    [[ -z "$name" || "$name" =~ ^[[:space:]]*# ]] && continue
    NAMES+=("$name")
    COMMANDS+=("$cmd")
done < "$CONFIG_FILE"

if [[ "${#NAMES[@]}" -eq 0 ]]; then
    zenity --error --text="$CONFIG_FILE has no valid entries." 2>/dev/null || true
    exit 1
fi

# --- Ask the user which browser to use ---
CHOICE=$(zenity --list \
    --title="Share to Browser" \
    --text="Open this link in:\n${URL}" \
    --column="Browser" \
    --width=420 --height=360 \
    "${NAMES[@]}" 2>/dev/null) || exit 0   # empty exit status on Cancel -> just exit

[[ -z "$CHOICE" ]] && exit 0

# --- Find the matching command template ---
CMD_TEMPLATE=""
for i in "${!NAMES[@]}"; do
    if [[ "${NAMES[$i]}" == "$CHOICE" ]]; then
        CMD_TEMPLATE="${COMMANDS[$i]}"
        break
    fi
done

if [[ -z "$CMD_TEMPLATE" ]]; then
    zenity --error --text="No command configured for '$CHOICE'." 2>/dev/null || true
    exit 1
fi

# --- Build argv safely: split the template on whitespace, substitute the
#     %u token with the URL as a single argument (never through a shell
#     string, so URLs containing &, ;, $, ` etc. can't be interpreted). ---
read -r -a TOKENS <<< "$CMD_TEMPLATE"
ARGS=()
for tok in "${TOKENS[@]}"; do
    if [[ "$tok" == "%u" ]]; then
        ARGS+=("$URL")
    else
        ARGS+=("$tok")
    fi
done

if [[ "${#ARGS[@]}" -eq 0 ]]; then
    zenity --error --text="Empty command for '$CHOICE'." 2>/dev/null || true
    exit 1
fi

# --- Launch, detached from this script ---
setsid "${ARGS[@]}" >/dev/null 2>&1 &
disown

if command -v notify-send >/dev/null 2>&1; then
    notify-send "Share to Other Browser" "Opening in $CHOICE"
fi

exit 0
